### ISSUE TITLE
Mobile website optimization 

### ISSUE THREAD

**Issue by chandradeep24** [ChandradeepC/FrogAI#1]
The website is currently not functioning optimally on mobile browsers. The css files in vite-project/src/ are all set to adapt when the width is less than 40rem and it works perfectly on the desktop but in mobile browsers there are some inconsistencies such as:

1. The top bar not extending the full length of the viewport on the landing page
2. The center column is overflowing horizontally on the landing page
3. Overall the UI is not optimized for mobile browsers as it requires a significant amount of scrolling to set the parameters and go through the recommendations so a better design would be helpful

**Comment by niyasrad** [comment]
Makes sense. If you could point me to the asset names, I can have a look through and manage the changes.

**Comment by chandradeep24** [comment]
The Landing Page .tsx and .css are in vite-project/src. Some elements in the Landing Page are borrowing CSS classes from App.css. The components for taking inputs have their styles in Component.css and the Recommendation boxes have their styles in Recommendations.css
